name: 'Get currency exchange rate'

on:
  schedule:
    - cron: '20 03 * * 2-6' # run every day at 03:30 UTC from Tuesday to Saturday
  workflow_dispatch:
    inputs:
      startDate:
        description: 'Start date'
        required: true
        type: string
        default: '2024-08-19'
      endDate:
        description: 'End date'
        required: true
        type: string
        default: '2024-08-19'
      currency:
        required: true
        default: 'USDFIXME'
        type: choice
        options:
          - USDFIXME
          - CNYFIXME
          - EURFIXME
          - BYNFIXME
          - CNYFIX
          - EURUSDFIXME
          - GOLDFIXME
          - HKDFIXME
          - TRYFIXME
          - USDCNYFIXME
          - USDKZTFIXME

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Update currency data
      CI_COMMIT_AUTHOR: GitHub Actions
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: DAILY. Get currency exchange rate
      if: ${{ github.event_name == 'schedule' }}
      run: |
        start=$(date --utc -d 'yesterday'  +%Y-%m-%d)
        end=$start
        python .github/workflows/getCurrency.py --start $start --end $end --currency USDFIXME
        python .github/workflows/getCurrency.py --start $start --end $end --currency EURFIXME
        python .github/workflows/getCurrency.py --start $start --end $end --currency CNYFIXME
    - name: MANUAL. Get currency exchange rate
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        python .github/workflows/getCurrency.py --start ${{ inputs.startDate }} --end ${{ inputs.endDate }} --currency ${{ inputs.currency }}
    - name: Commit and push build artifacts
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "github-actions@github.com"
        git add history/*.csv
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
