# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 'Get currency price from WSJ.com'

on:
  schedule:
    - cron: '15 17 * * 2-6' # run every day at 17:15 UTC from Tuesday to Saturday
  workflow_dispatch:
    inputs:
      startDate:
        description: 'Start date'
        required: true
        type: string
        default: '2008-12-10'
      endDate:
        description: 'End date'
        required: true
        type: string
        default: '2023-08-18'
      currency:
        description: 'Currency'
        required: true
        type: string
        default: 'USDRUB,EURRUB,CNYRUB'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Update currency data
      CI_COMMIT_AUTHOR: GitHub Actions
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: DAILY. Get currencies from WSJ.com
      if: ${{ github.event_name == 'schedule' }}
      run: |
        start = `date --utc -d '2008-12-10' +%m/%d/%Y`
        end   = `date --utc -d 'yesterday'  +%m/%d/%Y`
        python .github/workflows/getCurrency.py --start $start --end $end --currency ${{ inputs.currency }}
    - name: MANUAL. Get currencies from WSJ.com
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        python .github/workflows/getCurrency.py --start ${{ inputs.startDate }} --end ${{ inputs.endDate }} --currency ${{ inputs.currency }}
    - name: Commit and push build artifacts
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "github-actions@github.com"
        git add data/currency.json
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
