# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: '[manual] Get MOEX data'

on: 
  workflow_dispatch:
    inputs:
      startDate:
        description: 'Start date'
        required: true
        type: string
        default: '2023-07-17'
      endDate:
        description: 'End date'
        required: true
        type: string
        default: '2023-07-31'
      stepDays:
        description: 'Step in days'
        required: true
        type: number
        default: '7'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get data files from MOEX ISS
      run: |
        python .github/workflows/getData.py ${{ inputs.startDate }} ${{ inputs.endDate }} ${{ inputs.stepDays }}
    # Commit and push all changed files
    # https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html
    # Must only affect files that are listed in "paths-ignore"
    - name: Commit and push build artifacts
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "github-actions@github.com"
        git add data/iss/history/engines/stock/totals/boards/MRKT/*.json
        git commit -m "Manually collect and upload data from MOEX"
        git push