# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  release:
    branches: [ "main" ]
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get data files from MOEX ISS
      run: |
        python getData.py
    - name: Archive MOEX data
      uses: actions/upload-artifact@v3
      with:
        name: moex-iss-data
        path: data/iss/history/engines/stock/totals/boards/MRKT/*.json
