# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: '[daily] Get MOEX data'

on:
  schedule:
    - cron: '15 17 * * 2-6' # run every day at 17:15 UTC from Tuesday to Saturday
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Upload yesterday's MOEX data
      CI_COMMIT_AUTHOR: Github Actions
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get data files from MOEX ISS
      run: |
        python .github/workflows/getData.py
    # Commit and push all changed files
    # https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html
    # Must only affect files that are listed in "paths-ignore"
    - name: Commit and push build artifacts
      # Only run on main branch push (e.g. pull request merge)
      if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git add data/iss/history/engines/stock/totals/boards/MRKT/*.json
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
