name: 'Get MOEX data'

on:
  schedule:
    - cron: '20 00 * * 2-6' # run every day at 00:20 UTC from Tuesday to Saturday
    - cron: '0,15,30,45 7-20 * * 1-5' # run every 15 minutes from Monday to Friday
  workflow_dispatch:
    inputs:
      startDate:
        description: 'Start date'
        required: true
        type: string
        default: '2023-07-17'
      endDate:
        description: 'End date'
        required: true
        type: string
        default: '2023-07-31'
      stepDays:
        description: 'Step in days'
        required: true
        type: number
        default: 7

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Update MOEX data
      CI_COMMIT_AUTHOR: github-actions[bot]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      if: ${{ github.event.schedule != '0,15,30,45 7-20 * * 1-5' }}
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
    - name: Install dependencies
      if: ${{ github.event.schedule != '0,15,30,45 7-20 * * 1-5' }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: EVERY 15 MIN. Get current market data
      if: ${{ github.event.schedule == '0,15,30,45 7-20 * * 1-5' }}
      run: |
        CURRENT_DAY=$(TZ='UTC+3' date +'%Y-%m-%d')
        url="https://iss.moex.com/iss/engines/stock/markets/shares/securities.json?iss.meta=off"
        ua="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"
        response_code=$(curl --silent --output "data/iss/history/engines/stock/totals/boards/MRKT/securities-${CURRENT_DAY}.json" --user-agent "${ua}" "${url}")
        if [ "${response_code}" -ne 200 ]; then
          echo "Request failed with response code: ${response_code}"
          exit 1
        fi
    - name: DAILY. Get data files from MOEX ISS
      if: ${{ github.event.schedule == '20 00 * * 2-6' }}
      run: |
        python .github/workflows/getMoexData.py
    - name: MANUAL. Get data files from MOEX ISS
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        python .github/workflows/getMoexData.py ${{ inputs.startDate }} ${{ inputs.endDate }} ${{ inputs.stepDays }}
    - name: Commit and push build artifacts
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data/iss/history/engines/stock/totals/boards/MRKT/*.json
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
