name: 'Parse Securities'

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Parse securities
      CI_COMMIT_AUTHOR: github-actions[bot]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas
    - name: Update /data/issues-by-sector.tsv
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        python .github/workflows/parseSecurities.py
    - name: Commit and push build artifacts
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data/iss/securities/*.json data/*.tsv
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push