# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 'Process local data for the history chart'

on:
  workflow_run:
    workflows: ["Get MOEX data"]
    types:
      - completed
  schedule:
    - cron: '15 21 2 1 *' # run every year at Jan 1st 21:15 UTC
  workflow_dispatch:
    inputs:
      startDate:
        description: 'Start date'
        required: true
        type: string
        default: '2011-12-19'
      endDate:
        description: 'End date'
        required: true
        type: string
        default: '2011-12-21'
      stepDays:
        description: 'Step in days'
        required: true
        default: '1'
        type: number
      mode:
        description: 'Show capitalization by ticket, sector or total'
        required: true
        default: 'total'
        type: choice
        options:
          - total
          - ticket
          - sector

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: DAILY. Process local files
      if: ${{ github.event_name == 'workflow_run' }}
      run: |
        CURRENT_DATE=$(date +'%Y-%m-%d')
        python .github/workflows/processLocalData.py --start 2011-12-19 --end $CURRENT_DATE --step 15 --mode total --filename total.json
    
    - name: YEARLY. Process local files
      if: ${{ github.event_name == 'schedule' }}
      run: |
        LAST_YEAR=$(date -d "last year" +"%Y")
        python .github/workflows/processLocalData.py --start $LAST_YEAR-01-01 --end $LAST_YEAR-12-31 --step 7 --mode sector --filename $LAST_YEAR.json
    
    - name: MANUAL. Process local files
      run: |
        python .github/workflows/processLocalData.py --start ${{ inputs.startDate }} --end ${{ inputs.endDate }} --step ${{ inputs.stepDays }} --mode ${{ inputs.mode }} --filename "${{ inputs.startDate }}_${{ inputs.endDate }}_${{ inputs.stepDays }}_${{ inputs.mode }}.json"
    
    # Commit and push all changed files
    # https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html
    # Must only affect files that are listed in "paths-ignore"
    - name: Commit and push build artifacts
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "github-actions@github.com"
        git add history/*.json
        git commit -m "[manual] Process local data for the history chart"
        git push
