name: 'Update /data/issues-by-sector.tsv'

on:
  workflow_dispatch:
    # inputs:
    #   startDate:
    #     description: 'Start date'
    #     required: true
    #     type: string
    #     default: '2024-08-19'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Update /data/issues-by-sector.tsv
      CI_COMMIT_AUTHOR: GitHub Actions
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas
    - name: Update /data/issues-by-sector.tsv
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        python .github/workflows/getCurrency.py --start ${{ inputs.startDate }} --end ${{ inputs.endDate }} --currency ${{ inputs.currency }}
    - name: Commit and push build artifacts
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "github-actions@github.com"
        git add data/iss/securities/*.json data/*.tsv
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
